### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by melsman** [diku-dk/segmented#2]
The example in the README.md file is erroneous: the size of the flags array does not match the size of the value array.

**Comment by athas** [comment]
Cosmin suggested that we change segmented_reduce to not take a flag array, but instead an array of segments lengths.  Maybe that's the change we should make.

**Comment by melsman** [comment]
I think we should support both kinds... Maybe we could add flag-segmented
versions in a `flags` submodule inside the `segmented` module...
